services:
  - type: web
    name: zyro-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn zyro_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12