# Generated by Django 5.2.13 on 2026-05-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='review',
            name='admin_reply',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Reply'),
        ),
        migrations.AddField(
            model_name='review',
            name='admin_reply_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reply Date'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified Purchase'),
        ),
    ]
