# Generated by Django 5.2.13 on 2026-05-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='user_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='bot_response',
            new_name='response',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_operator_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('operator', 'Operator'), ('ai', 'AI Assistant')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='operator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session_id',
            field=models.CharField(db_index=True, default='temp_session', max_length=100),
            preserve_default=False,
        ),
    ]
